name: deploy-react-project
run-name: ${{ github.actor }} is deploying project-pages
on:
  push:
    branches:
      - "main"
jobs:
  deploy-react-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: setup git
      - run: |
          git config --global user.email "${{github.event.pusher.email}}"
          git config --global user.name "${{github.actor}}"
      - name: install npm
        run: npm install
      - name: build project-pages
        run: PUBLIC_URL=/${{ github.event.repository.name}} npm run build
      - name: deploy-react-project
        run: |
          mkdir ./main
          git init -b gh-pages ./main
          cd ./gh-pages
          git remote add -t gh-pages origin1 \
          https://git:${{github.token}}@github.com/${{ github.repository }}.git
          git pull origin1 gh-pages
          rm -rf ./*
          cp -rf ../build/* ./
          git add .
          git commit -m "${{ github.actor }} deploy"
          git push origin1 gh-pages
          cd ..


    